### ISSUE TITLE
Cannot get the app to connect

### ISSUE THREAD

**Issue by CraigSuch** [aleksei-klv/dex-vnc-viewer#1]
Hi. I am very interested in a VNC client for Samsung Dex and came across your project. I am having trouble connect to a TightVNC server running on Windows 10. The app keeps egts stuck with the message "Establishing Handshatre... Please wait" DO you have any suggestion for me?

**Comment by aleksei-klv** [comment]
Hi, @CraigSuch . Sorry for the late response. I think problem is in Windows Firewall. Try to turn it off.
